// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWhvl40-yYPC2WY3LSMf1xbiIeQ0dwL_A',
    appId: '1:1027311554763:web:f24885728e61e91f624b4e',
    messagingSenderId: '1027311554763',
    projectId: 'auth-4da56',
    authDomain: 'auth-4da56.firebaseapp.com',
    databaseURL:
        'https://auth-4da56-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-4da56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeHFnLP55abdPkjlihA4u9XSgjQeL1YgY',
    appId: '1:1027311554763:android:0d50e4d48619fd83624b4e',
    messagingSenderId: '1027311554763',
    projectId: 'auth-4da56',
    databaseURL:
        'https://auth-4da56-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-4da56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Pf7-aMFES-dJnfEoCbfMhJYfibfrBo8',
    appId: '1:1027311554763:ios:0f6a952bf6f6f374624b4e',
    messagingSenderId: '1027311554763',
    projectId: 'auth-4da56',
    databaseURL:
        'https://auth-4da56-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-4da56.appspot.com',
    iosBundleId: 'com.example.emaill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Pf7-aMFES-dJnfEoCbfMhJYfibfrBo8',
    appId: '1:1027311554763:ios:0f6a952bf6f6f374624b4e',
    messagingSenderId: '1027311554763',
    projectId: 'auth-4da56',
    databaseURL:
        'https://auth-4da56-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-4da56.appspot.com',
    iosBundleId: 'com.example.emaill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWhvl40-yYPC2WY3LSMf1xbiIeQ0dwL_A',
    appId: '1:1027311554763:web:33fb5ffd66e9d444624b4e',
    messagingSenderId: '1027311554763',
    projectId: 'auth-4da56',
    authDomain: 'auth-4da56.firebaseapp.com',
    databaseURL:
        'https://auth-4da56-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-4da56.appspot.com',
  );
}
